jobTitle: Product Engineer
companyName: Zero One Group
companyLogo: /images/companyLogos/product-engineer-zero-one-group/companyLogo.jpeg
shortDescription: >-
  Zero One Group it's an agency that help businesses redefine future
  possibilities with comprehensive strategic solutions today
startDate: '2021-04-16'
endDate: '2022-10-06'
draft: false
redirect:
  discriminant: true
  value:
    url: https://zero-one-group.com
techStack:
  - chakra-ui
  - next-js
  - typescript
  - react-query
  - map-box
  - nivo
  - fastify
